{% set name = "web3" %}
{% set version = "5.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aea1b148c0bf95c0439a48cc6f97ebb183fb29716aea9f8b8f2894378959a2e0

build:
  number: 0
  # skip due to hypothesis < 4 not playing nice with pytest https://github.com/ethereum/eth-abi/issues/143 and https://github.com/HypothesisWorks/hypothesis/issues/1943
  skip: false
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - eth-abi >=2.0.0b6,<3.0.0
    - eth-account >=0.5.2,<0.6.0
    - eth-hash >=0.2.0,<1.0.0
    - eth-typing >=2.0.0,<3.0.0
    - eth-utils >=1.8.4,<2.0.0
    - hexbytes >=0.1.0,<1.0.0
    - ipfshttpclient >=0.4.13,<1
    - jsonschema >=3.2.0,<4.0.0
    - lru-dict >=1.1.6,<2.0.0
    - protobuf >=3.10.0,<4
    - pywin32 >=223  # [win]
    - requests >=2.16.0,<3.0.0
    - typing-extensions >=3.7.4.1,<4  # [py<38]
    - websockets >=9.1.0,<10
    - aiohttp >=3.7.4.post0,<4

test:
  imports:
    - web3
    - ens
    - ethpm

about:
  home: https://github.com/ethereum/web3.py
  summary: Web3.py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
